### ISSUE TITLE
"evalnodes can only be accessed via the class, not instance"

### ISSUE THREAD

**Issue by sorying** [manahl/mdf#23]
Hi there - starting my journey in using MDF. A major question I have is... why evalnodes can only be accessed via the class, not instance?

Specifically, here's the dummy example I am trying to construct. 

```
class Fund(object):
    data_source = varnode(default='isin')
    data_source_id = varnode()

    @evalnode()
    def __str__(self):
        return '{} ({}: {})'.format(self.long_name, self.data_source, self.data_source_id)

    @evalnode()
    def long_name(self):
        return self.row_getter()['long_name']

    @evalnode()
    def mgmt_fee(self):
        return self.row_getter()['mgmt_fee']

    @evalnode()
    def row_getter(self):
        return self.fund_ref_data_by_isin()[self.data_source_id()]

    @evalnode()
    def fund_ref_data_by_isin(self):
        df = pd.read_excel('data.xlsx', 'funds', index_col='data_source_id')
        return df.to_dict(orient='index')
```

'data.xlsx' basically has a flat table key by the ISIN and bunch of reference data.

Essentially I want these to work within the same context
```
ctx = MDFContext()
fund1 = Fund()
fund2 = Fund()

ctx[fund1.data_source_id] = 'IE00B12V2W34'
ctx[fund2.data_source_id] = 'IE00B1XK9C88'
print(ctx[fund1.long_name])
print(ctx[fund2.long_name])
```

Right now I hit the error
```AssertionError: evalnodes can only be accessed via the class, not instance```

But if we can't apply MDF into instance.... then what would be the recommended way to achieve my use case above? I can't imagine having to create 2 context or to have to toggle them around?

Also.... trying to see if there are any larger example code of MDF. It's actually an amazing tool in modelling dependency (conceptually it's really like Excel but better). So would be great to see some large scale example....

**Comment by tonyroberts** [comment]
Hi,

instances are essentially classes with state (ie. the self object). This doesn't sit well with the idea that in mdf all nodes are pure functions which are stateless. This is why mdf nodes cannot be instance methods, only class or static methods.

In your example, you could forget about having evalnodes on your fund object, and instead may the fund objects values of a varnode, and have your analytics use that - something like...

```python
fund = varnode()
funds = varnode(value=[fund1, fund2])

@evalnode
def fund_level_analytic():
    current_fund = fund()
    # do some work
    return result

@evalnode
def aggregated_result():
    all_funds = funds()
    fund_values = shift(fund_level_analytic, fund, all_funds)
    # do some work on fund values
    return result
```

You could structure those to be static methods on your fund class, with a class varnode 'current_fund' or something like that.

By shifting, mdf is actually creating new contexts to hold the state for the common nodes with the different values for the fund varnode - but the shift function takes care of that for you, and ensures that the contexts are really only shallow copies, only capturing state for anything that's different from their base contexts.

There's a section about shifted contexts in the docs here: http://mdf-data-flow-programming-toolkit.readthedocs.io/en/latest/contexts.html#shifted-contexts

Unfortunately all the more complex examples of MDF to date have been propriatory and so there are no publicly available large scale examples. If you manage to create some code that would make a good example please think about contributing it back!

Best regards,
Tony

**Comment by sorying** [comment]
Thanks very much @tonyroberts for your great response. Will have a deeper look into shifted context, and will fore sure to contribute back as I start to get a hold on how to use it well.... many thanks!

**Comment by sorying** [comment]
Hi @tonyroberts , re-opening this issue hoping to get your advice. (been scratching my head to get a functional example....)

In order to illustrate my use case, here's the "dummy example" I am hoping MDF could work with. Essentially just 2 portfolio "User" object - they hold positions; You have "Product" object that price each product. The total price of a "user portfolio" is the sum of price of the underlying products times quantity they hold. Price of product are date-dependent.

To me, this sounds like a very natural way to use MDF to represent the relationship.

However, because MDF doesn't allow you to apply Node concept on object instance, I have been scratching my head hard as to get this work....

<Pls see attached code sample --- the Markdown is not showing the code correctly>
[mdf_eg.txt](https://github.com/manahl/mdf/files/814161/mdf_eg.txt)



Hence, essentially my 2 questions are:
1) is it at all possible to make MDF work with object instance, and
2) if not..... what's your recommended way in solving my problem above?

I have been using ZODB (http://www.zodb.org/en/latest/) in persisting my classes; hence when those objects are being retrieved, it's already in "object" form. If I can represent all the inter-object dependency via MDF, that will be superb.

By the way, on side note, EPD Traits library with the "depends_on" kind of do what I was hoping to achieve. However, the dependency has to be specified explicitly (rather than implicitly parsed like in MDF). How could the similar concept be implemented here?

http://stackoverflow.com/questions/9959424/difference-between-using-properties-or-trait-handlers-to-set-dependent-variable
http://stackoverflow.com/questions/27444786/property-trait-with-depends-on

**Comment by tonyroberts** [comment]
Something like this? (not tried running it, but maybe it will give you some ideas).

```python
class Product(object):
    ticker = varnode()

    @evalnode()
    def price(cls):
        return prices()[now()][cls.ticker()]

class User(object):
    user_id = varnode()

    @evalnode()
    def holdings(cls):
        rv = positions()[now()][cls.user_id()]
        return [(ticker, v) for k, v in rv.items()]

    @evalnode()
    def price(cls):
        holdings = cls.holdings()
        prices = shift(Product.price, Product.ticker, [ticker for (ticker, qty) in holdings])
        quantities = [qty for (ticker, qty) in holdings]
        return sum([p * q for p, q in zip(prices, quantity)])
```

**Comment by sorying** [comment]
Thanks so much for the pointer. It worked after some slight modification. The trick really seems to be using 'shift' in establishing inter-object, and multiple relationship. I will continue to refine my example to see if I can convert most of the implementation into MDF style.

I will consolidate those snippets and contribute back to the community with a larger example.

From a Technology Stack standpoint, how do you store your underlying data? Originally I was hoping to leverage ZODB (object database for Python) with MDF. In that context, I will actually be storing lots of "Product" and "User" objects where their fields are being pickled. 

In such context, however though, I won't be "shift"-ing Product.ticker across all ticker holding in-memory, and instead those Product objects will already be somewhere in the Database. 

Curious how you will do it your end...? Perhaps Excel / Dataframe given you are Pyxll expert.....??

**Comment by sorying** [comment]
For the record, this is code that works ... thanks

```
from datetime import datetime
from mdf import varnode, evalnode, now, MDFContext, shift

def prices():
    return {
        datetime(2017, 2, 20): {
            'SPY': 200,
            'AGG': 100,
            'FB': 130
        },
        datetime(2017, 2, 21): {
            'SPY': 205,
            'AGG': 98,
            'FB': 135,
        }
    }

def positions():
    return {
        datetime(2017, 2, 20): {
            'user1': {
                'SPY': 10,
                'AGG': 5
            },
            'user2': {
                'SPY': 20,
                'FB': 25,
            }
        },
        datetime(2017, 2, 21): {
            'user1': {
                'SPY': 11,
                'AGG': 4
            },
            'user2': {
                'FB': 30,
            }
        }
    }

class Product(object):
    ticker = varnode()

    @evalnode()
    def price(cls):
        return prices()[now()][cls.ticker()]

class User(object):
    user_id = varnode()

    @evalnode()
    def holdings(cls):
        rv = positions()[now()][cls.user_id()]
        return [(k, v) for k, v in rv.items()]

    @evalnode()
    def price(cls):
        holdings = cls.holdings()
        this_prices = shift(Product.price, Product.ticker, [ticker for (ticker, qty) in holdings])
        quantities = [qty for (ticker, qty) in holdings]
        return sum([p * q for p, q in zip(this_prices, quantities)])


ctx = MDFContext(datetime(2017, 2, 20))
ctx[User.user_id] = 'user1'
print(ctx[User.price])
ctx.set_date(datetime(2017,2,21))
print(ctx[User.price])

```
